From c58eb603627592fa82d4d7d11d07a3b552c70b32 Mon Sep 17 00:00:00 2001
From: Petr Lautrbach <plautrba@redhat.com>
Date: Fri, 1 Jul 2016 17:16:16 +0200
Subject: [PATCH] framework: Update translations from
 https://fedora.zanata.org/iteration/view/setroubleshoot/master

---
 framework/po/as.po       |  70 +++---------------------
 framework/po/bg.po       |  70 +++---------------------
 framework/po/bn.po       |  70 +++---------------------
 framework/po/bn_IN.po    |  70 +++---------------------
 framework/po/ca.po       |  74 +++----------------------
 framework/po/cs.po       |  71 +++---------------------
 framework/po/da.po       |  71 +++---------------------
 framework/po/de.po       |  72 +++----------------------
 framework/po/el.po       |  70 +++---------------------
 framework/po/en_GB.po    |  70 +++---------------------
 framework/po/es.po       |  72 +++----------------------
 framework/po/eu.po       |  70 +++---------------------
 framework/po/fi.po       |  70 +++---------------------
 framework/po/fr.po       |  71 +++---------------------
 framework/po/gl.po       |  70 +++---------------------
 framework/po/gu.po       |  70 +++---------------------
 framework/po/he.po       |  70 +++---------------------
 framework/po/hi.po       |  70 +++---------------------
 framework/po/hr.po       |  70 +++---------------------
 framework/po/hu.po       |  71 +++---------------------
 framework/po/it.po       |  72 +++----------------------
 framework/po/ja.po       |  70 +++---------------------
 framework/po/kn.po       |  71 +++---------------------
 framework/po/ko.po       |  70 +++---------------------
 framework/po/mai.po      |  70 +++---------------------
 framework/po/ml.po       |  72 +++----------------------
 framework/po/mr.po       |  70 +++---------------------
 framework/po/ms.po       |  70 +++---------------------
 framework/po/nb.po       |  70 +++---------------------
 framework/po/nds.po      |  70 +++---------------------
 framework/po/nl.po       |  72 +++----------------------
 framework/po/or.po       |  70 +++---------------------
 framework/po/pa.po       |  70 +++---------------------
 framework/po/pl.po       |  76 +++-----------------------
 framework/po/pt.po       |  71 +++---------------------
 framework/po/pt_BR.po    |  70 +++---------------------
 framework/po/ru.po       |  70 +++---------------------
 framework/po/sk.po       |  70 +++---------------------
 framework/po/sr.po       |  70 +++---------------------
 framework/po/sr@latin.po |  70 +++---------------------
 framework/po/sv.po       |  71 +++---------------------
 framework/po/ta.po       |  70 +++---------------------
 framework/po/te.po       |  70 +++---------------------
 framework/po/th.po       |  70 +++---------------------
 framework/po/tr.po       |  70 +++---------------------
 framework/po/uk.po       |  70 +++---------------------
 framework/po/zh_CN.po    | 138 ++++++++++++++---------------------------------
 framework/po/zh_TW.po    |  70 +++---------------------
 48 files changed, 325 insertions(+), 3130 deletions(-)

diff --git a/framework/po/as.po b/framework/po/as.po
index b67f8b5..e52787f 100644
--- a/framework/po/as.po
+++ b/framework/po/as.po
@@ -13,7 +13,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -23,7 +23,7 @@ msgstr ""
 "as/)\n"
 "Language: as\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -42,9 +42,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "পোৰ্ট %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "অজ্ঞাত"
 
@@ -171,7 +171,7 @@ msgstr "এইটোত"
 msgid "Occurred"
 msgstr "ঘটিত"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "অৱস্থা"
 
@@ -353,64 +353,6 @@ msgstr ""
 "আপুনি $SOURCE_BASE_PATH -ক $TARGET_BASE_PATH $TARGET_CLASS ত $ACCESS অভিগম "
 "দিব বিচাৰে"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ইনপুট: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "পাছৱাৰ্ড সুমুৱাওক"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "পাছৱাৰ্ড: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux সমাধান"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "কমান্ড"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "কমান্ড সঞ্চালন"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "কমান্ড বন্ধ কৰক"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "সতৰ্কবাৰ্তা: কমান্ডৰ সঠিক মান পৰীক্ষণৰ বাবে ব্যৱহাৰকাৰী দায়ী।"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "এতিয়াও সঞ্চালিত নহয়"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "চলমান..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "বিঘ্নিত, %d সংকেতত প্ৰস্থান কৰা হ'ব"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "সফল"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "ব্যৰ্থ, প্ৰস্থানকালৰ অৱস্থা = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "সমাপ্ত: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/bg.po b/framework/po/bg.po
index 14827c1..38b2990 100644
--- a/framework/po/bg.po
+++ b/framework/po/bg.po
@@ -11,7 +11,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "language/bg/)\n"
 "Language: bg\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "порт %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Непознат"
 
@@ -169,7 +169,7 @@ msgstr "На това"
 msgid "Occurred"
 msgstr "Настъпи"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Статус"
 
@@ -351,64 +351,6 @@ msgstr ""
 "искате да позволите на $SOURCE_BASE_PATH да има $ACCESS достъп до "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Вход: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Въведете парола"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Парола: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux fix"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Команда"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Стартирай команда"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Спри команда"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Внимание: Вие сте отговорни да проверите дали тази команда е правилна"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Не е стартирано още"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Работи..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Прекъснато, излизане при сигнал %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Успех"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Неуспешно, статус на завършване = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Готово: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/bn.po b/framework/po/bn.po
index 018556c..1f8823c 100644
--- a/framework/po/bn.po
+++ b/framework/po/bn.po
@@ -15,7 +15,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -25,7 +25,7 @@ msgstr ""
 "bn/)\n"
 "Language: bn\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -44,9 +44,9 @@ msgstr ""
 msgid "port %s"
 msgstr "পোর্ট %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "অজানা"
 
@@ -173,7 +173,7 @@ msgstr "চিহ্নিত সামগ্রীর ক্ষেত্রে"
 msgid "Occurred"
 msgstr "ঘটিত"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "অবস্থা"
 
@@ -355,64 +355,6 @@ msgstr ""
 "‌$SOURCE_BASE_PATH-কে $TARGET_BASE_PATH $TARGET_CLASS-র জন্য $ACCESS "
 "ব্যবহারের অধিকার প্রদান করতে ইচ্ছুক হলে"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ইনপুট: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "পাসওয়ার্ড লিখুন"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "পাসওয়ার্ড: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux সমাধান"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "কমান্ড"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "কমান্ড সঞ্চালন"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "কমান্ড বন্ধ করুন"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "সতর্কবার্তা: কমান্ডের সঠিক মান পরীক্ষণের জন্য ব্যবহারকারী দায়ী।"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "এখনো সঞ্চালিত হয়নি"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "চলমান..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "বিঘ্নিত, %d সংকেতে প্রস্থান করা হবে"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "সফল"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "ব্যর্থ, প্রস্থানকালে অবস্থা = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "সমাপ্ত: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/bn_IN.po b/framework/po/bn_IN.po
index 4c40655..f2968a3 100644
--- a/framework/po/bn_IN.po
+++ b/framework/po/bn_IN.po
@@ -12,7 +12,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -22,7 +22,7 @@ msgstr ""
 "language/bn_IN/)\n"
 "Language: bn-IN\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -41,9 +41,9 @@ msgstr "নীতি;নিরাপত্তা;selinux;avc;অনুমতি;
 msgid "port %s"
 msgstr "পোর্ট %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "অজানা"
 
@@ -170,7 +170,7 @@ msgstr "চিহ্নিত সামগ্রীর ক্ষেত্রে"
 msgid "Occurred"
 msgstr "ঘটিত"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "অবস্থা"
 
@@ -352,64 +352,6 @@ msgstr ""
 "‌$SOURCE_BASE_PATH-কে $TARGET_BASE_PATH $TARGET_CLASS-র জন্য $ACCESS "
 "ব্যবহারের অধিকার প্রদান করতে ইচ্ছুক হলে"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ইনপুট: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "পাসওয়ার্ড লিখুন"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "পাসওয়ার্ড: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux সমাধান"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "কমান্ড"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "কমান্ড সঞ্চালন"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "কমান্ড বন্ধ করুন"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "সতর্কবার্তা: কমান্ডের সঠিক মান পরীক্ষণের জন্য ব্যবহারকারী দায়ী।"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "এখনো সঞ্চালিত হয়নি"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "চলমান..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "বিঘ্নিত, %d সংকেতে প্রস্থান করা হবে"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "সফল"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "ব্যর্থ, প্রস্থানকালে অবস্থা = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "সমাপ্ত: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/ca.po b/framework/po/ca.po
index ec7030d..b375d02 100644
--- a/framework/po/ca.po
+++ b/framework/po/ca.po
@@ -10,17 +10,17 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
-"PO-Revision-Date: 2015-10-17 02:56-0400\n"
+"PO-Revision-Date: 2015-10-09 04:41-0400\n"
 "Last-Translator: Robert Antoni Buj Gelonch <rbuj@fedoraproject.org>\n"
 "Language-Team: Catalan (http://www.transifex.com/projects/p/fedora/language/"
 "ca/)\n"
 "Language: ca\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -39,9 +39,9 @@ msgstr "política;seguretat;selinux;avc;permisos;mac;alerta;sealert;"
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Desconegut"
 
@@ -170,7 +170,7 @@ msgstr "Sobre"
 msgid "Occurred"
 msgstr "Ocurrències"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Estat"
 
@@ -352,66 +352,6 @@ msgstr ""
 "voleu permetre que $SOURCE_BASE_PATH tingui accés de $ACCESS a "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Entrada:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Introduïu la contrasenya"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Contrasenya: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Correcció del SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Ordre"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Executa l'ordre"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Atura l'ordre"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Advertència: sou el responsable de comprovar que aquesta ordre sigui "
-"correcta"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Encara no s'ha executat"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Executant..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "S'ha interromput i se surt pel senyal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Correctament"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Ha fallat i se surt amb l'estat %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Fet: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/cs.po b/framework/po/cs.po
index 0ebc8a6..551ea94 100644
--- a/framework/po/cs.po
+++ b/framework/po/cs.po
@@ -12,7 +12,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -22,7 +22,7 @@ msgstr ""
 ")\n"
 "Language: cs\n"
 "Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -41,9 +41,9 @@ msgstr "strategie;bezpečnost;selinux;avc;oprávnění;mac;alert;sealert;"
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Neznámé"
 
@@ -170,7 +170,7 @@ msgstr "Na tomto"
 msgid "Occurred"
 msgstr "Nastal"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Stav"
 
@@ -352,65 +352,6 @@ msgstr ""
 "chcete povolit, aby $SOURCE_BASE_PATH mělo přístup $ACCESS k "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Vstup: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Zadejte heslo"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Heslo: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Oprava SELinuxu"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Příkaz"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Spustit příkaz"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Zastavit příkaz"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Varování: Zkontrolovat, že je tento příkaz správný, je vaše zodpovědnost"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Ještě nespuštěno"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Spouštím..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Přerušeno, konec po signálu %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Úspěch"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Selhalo, stav = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Hotovo: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/da.po b/framework/po/da.po
index d3dbeda..2fc90c5 100644
--- a/framework/po/da.po
+++ b/framework/po/da.po
@@ -11,7 +11,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "da/)\n"
 "Language: da\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr "politik;sikkerhed;selinux;avc;rettighed;mac;advarsel;sealert;"
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Ukendt"
 
@@ -169,7 +169,7 @@ msgstr "På denne"
 msgid "Occurred"
 msgstr "Opstod"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Status"
 
@@ -351,65 +351,6 @@ msgstr ""
 "vil du tillade $SOURCE_BASE_PATH til at have $ACCESS-adgang til "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Input: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Indtast adgangskode"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Adgangskode: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux rettelse"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Kommando"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Kør kommando"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Afbryd kommando"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Advarsel: Du er ansvarlig for at kontrollere om denne kommando er korrekt"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Ikke kørt endnu"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Kører..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Afbrudt, afslutter på signal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Succes"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Fejlede, afslutnings status = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Færdig: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/de.po b/framework/po/de.po
index fc5645b..c9d5042 100644
--- a/framework/po/de.po
+++ b/framework/po/de.po
@@ -23,7 +23,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -33,7 +33,7 @@ msgstr ""
 "de/)\n"
 "Language: de\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -52,9 +52,9 @@ msgstr "Richtlinie;Sicherheit;selinux;avc;Berechtigung;mac;alert;sealert;"
 msgid "port %s"
 msgstr "Port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Unbekannt"
 
@@ -181,7 +181,7 @@ msgstr "auf dies"
 msgid "Occurred"
 msgstr "aufgetreten"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Status"
 
@@ -362,66 +362,6 @@ msgstr ""
 "Sie $SOURCE_BASE_PATH den Zugriff $ACCESS auf $TARGET_BASE_PATH "
 "$TARGET_CLASS erlauben wollen"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Eingabe: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Passwort eingeben"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Passwort: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux-Korrektur"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Befehl"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Befehl ausführen"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Befehl stoppen"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Warnung: Sie sind dafür verantwortlich, zu überprüfen, ob der Befehl korrekt "
-"ist!"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Noch nicht ausgeführt"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Wird ausgeführt ..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Unterbrochen, Abbruch auf Signal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Erfolg"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Fehlgeschlagen, Abbruchstatus = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Fertig: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/el.po b/framework/po/el.po
index d393a83..2bd702b 100644
--- a/framework/po/el.po
+++ b/framework/po/el.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 ")\n"
 "Language: el\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Άγνωστο"
 
@@ -158,7 +158,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Κατάσταση"
 
@@ -336,64 +336,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr ""
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Εισάγετε συνθηματικό:"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Συνθηματικό:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr ""
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr ""
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr ""
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr ""
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr ""
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr ""
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Επιτυχία"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr ""
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/en_GB.po b/framework/po/en_GB.po
index 716a54e..97fc2b0 100644
--- a/framework/po/en_GB.po
+++ b/framework/po/en_GB.po
@@ -11,7 +11,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "fedora/language/en_GB/)\n"
 "Language: en-GB\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr ""
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Unknown"
 
@@ -169,7 +169,7 @@ msgstr "On this"
 msgid "Occurred"
 msgstr "Occurred"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Status"
 
@@ -351,64 +351,6 @@ msgstr ""
 "you want to allow $SOURCE_BASE_PATH to have $ACCESS access on the "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Input: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Enter Password"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Password: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux Fix"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Command"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Run Command"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Stop Command"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Warning: You are responsible for verifying this command is correct"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Not Run Yet"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Running..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Interrupted, exit on signal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Success"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Failed, exit status = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Done: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/es.po b/framework/po/es.po
index 2a649be..4a1fb79 100644
--- a/framework/po/es.po
+++ b/framework/po/es.po
@@ -18,7 +18,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -28,7 +28,7 @@ msgstr ""
 "es/)\n"
 "Language: es\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -47,9 +47,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "puerto %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Desconocido"
 
@@ -176,7 +176,7 @@ msgstr "En esta"
 msgid "Occurred"
 msgstr "Ocurrido"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Estado"
 
@@ -358,66 +358,6 @@ msgstr ""
 "desea permitir que $SOURCE_BASE_PATH tenga acceso $ACCESS al "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Entrada:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Ingrese la contraseña"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Contraseña:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Corrección de SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Comando"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Ejecutar comando"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Detener comando"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Advertencia: usted es el responsable de verificar que este comando sea "
-"correcto"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "No ejecutado todavía"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Ejecutando..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Interrumpido, salida por señal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Éxito"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Falló, estado de salida = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Hecho:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/eu.po b/framework/po/eu.po
index 7317192..7e30951 100644
--- a/framework/po/eu.po
+++ b/framework/po/eu.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 "eu/)\n"
 "Language: eu\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr "%s ataka"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Ezezaguna"
 
@@ -158,7 +158,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Egoera"
 
@@ -336,64 +336,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr ""
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr ""
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr ""
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr ""
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Komandoa"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Exekutatu komandoa"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Gelditu komandoa"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr ""
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Exekutatzen..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr ""
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Eginda:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/fi.po b/framework/po/fi.po
index c05c990..ccaf146 100644
--- a/framework/po/fi.po
+++ b/framework/po/fi.po
@@ -11,7 +11,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "fi/)\n"
 "Language: fi\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr ""
 msgid "port %s"
 msgstr "portti %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Tuntematon"
 
@@ -169,7 +169,7 @@ msgstr "Tällä"
 msgid "Occurred"
 msgstr "Tapahtui"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Tila"
 
@@ -351,64 +351,6 @@ msgstr ""
 "haluat sallia lähteelle $SOURCE_BASE_PATH pääsyn $ACCESS kohteeseen "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Syöte: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Anna salasana"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Salasana: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux-korjaus"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Komento"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Suorita komento"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Pysäytä komento"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Varoitus: Varmista että tämä komento on oikein"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Ei ole vielä suoritettu"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Suoritetaan..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Keskeytetty signaalilla %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Onnistui"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Epäonnistui, lopetustila %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Valmis: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/fr.po b/framework/po/fr.po
index fee3d37..9466499 100644
--- a/framework/po/fr.po
+++ b/framework/po/fr.po
@@ -22,7 +22,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -32,7 +32,7 @@ msgstr ""
 "fr/)\n"
 "Language: fr\n"
 "Plural-Forms: nplurals=2; plural=(n > 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -51,9 +51,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Inconnu"
 
@@ -180,7 +180,7 @@ msgstr "Sur"
 msgid "Occurred"
 msgstr "S'est déclaré"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "État"
 
@@ -362,65 +362,6 @@ msgstr ""
 "vous souhaitez autoriser $SOURCE_BASE_PATH à accéder à $ACCESS sur "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Saisie :"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Entrez le mot de passe"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Mot de passe :"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Correctif SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Commande"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Lancer la commande"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Arrêter la commande"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Attention : il vous appartient de vérifier que cette commande soit correcte"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Pas encore démarré"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "En cours d'exécution..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Interrompu, sortie sur signal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Succès"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Échoué, état de sortie = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Terminé :"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/gl.po b/framework/po/gl.po
index 8ad9550..f37ac98 100644
--- a/framework/po/gl.po
+++ b/framework/po/gl.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 "gl/)\n"
 "Language: gl\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr "porto %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Descoñecido"
 
@@ -158,7 +158,7 @@ msgstr "Nesta"
 msgid "Occurred"
 msgstr "Ocorrido"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Estado"
 
@@ -338,64 +338,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr ""
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr ""
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr ""
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr ""
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr ""
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr ""
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr ""
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr ""
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr ""
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr ""
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr ""
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/gu.po b/framework/po/gu.po
index 078ff19..5238a4d 100644
--- a/framework/po/gu.po
+++ b/framework/po/gu.po
@@ -13,7 +13,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -23,7 +23,7 @@ msgstr ""
 "gu/)\n"
 "Language: gu\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -42,9 +42,9 @@ msgstr "પોલિસી;સુરક્ષા;selinux;avc;પરવાનગ
 msgid "port %s"
 msgstr "પોર્ટ %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "અજ્ઞાત"
 
@@ -171,7 +171,7 @@ msgstr "આની પર"
 msgid "Occurred"
 msgstr "ઉદ્ભવ્યુ"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "પરિસ્થિતિ"
 
@@ -353,64 +353,6 @@ msgstr ""
 "તમે $TARGET_BASE_PATH $TARGET_CLASS પર $ACCESS પ્રવેશ આપવા માટે "
 "$SOURCE_BASE_PATH ને પરવાનગી આપવા માંગો છો"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ઈનપુટ: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "પાસવર્ડ દાખલ કરો"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "પાસવર્ડ: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux Fix"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "આદેશ"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "આદેશ ચલાવો"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "આદેશ અટકાવો"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "ચેતવણી: તમે આ આદેશ સાચો છે તેની ખાતરી કરવા માટે જવાબદાર છો"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "હજુ ચાલ્યું નથી"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "ચાલી રહ્યું છે..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "અટકાવાયેલ, સંકેત %d પર બહાર નીકળો"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "સફળ"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "નિષ્ફળ, બહાર નીકળવાની પરિસ્થિતિ = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "પૂર્ણ: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/he.po b/framework/po/he.po
index ca2a477..053bf49 100644
--- a/framework/po/he.po
+++ b/framework/po/he.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 "he/)\n"
 "Language: he\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "לא ידוע"
 
@@ -158,7 +158,7 @@ msgstr "על זה"
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "מצב"
 
@@ -336,64 +336,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr ""
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr ""
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr ""
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr ""
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr ""
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr ""
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr ""
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr ""
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr ""
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr ""
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr ""
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/hi.po b/framework/po/hi.po
index 30c1288..d5f3229 100644
--- a/framework/po/hi.po
+++ b/framework/po/hi.po
@@ -14,7 +14,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -24,7 +24,7 @@ msgstr ""
 ")\n"
 "Language: hi\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -43,9 +43,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "अज्ञात"
 
@@ -172,7 +172,7 @@ msgstr "इस पर"
 msgid "Occurred"
 msgstr "पैदा हुआ"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "स्थिति"
 
@@ -354,64 +354,6 @@ msgstr ""
 "आप $SOURCE_BASE_PATH को $ACCESS पहुँच $TARGET_BASE_PATH $TARGET_CLASS पर "
 "पाने के लिए अनुमति देना चाहते हैं"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "इनपुट: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "कूटशब्द दाखिल करें"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "कूटशब्द: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux फिक्स"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "कमांड"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "कमांड चलाएँ"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "कमांड रोकें"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "चेतावनी: आप इस कमांड को जांचने के लिए उत्तरदायी है कि यह सही है"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "अब चला नहीं"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "चल रहा है..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "व्यवधान, %d संकेत पर बाहर"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "सफल"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "विफल, स्थिति से बाहर निकलें = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "संपन्न: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/hr.po b/framework/po/hr.po
index d0b4993..19cfe51 100644
--- a/framework/po/hr.po
+++ b/framework/po/hr.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -19,7 +19,7 @@ msgstr ""
 "Language: hr\n"
 "Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<="
 "4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -38,9 +38,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Nepoznato"
 
@@ -159,7 +159,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr ""
 
@@ -337,64 +337,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr ""
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr ""
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr ""
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr ""
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr ""
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr ""
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr ""
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr ""
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr ""
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr ""
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr ""
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/hu.po b/framework/po/hu.po
index 1d1206f..1ee5011 100644
--- a/framework/po/hu.po
+++ b/framework/po/hu.po
@@ -13,7 +13,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -23,7 +23,7 @@ msgstr ""
 "language/hu/)\n"
 "Language: hu\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -42,9 +42,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Ismeretlen"
 
@@ -171,7 +171,7 @@ msgstr "Ezen"
 msgid "Occurred"
 msgstr "Történt"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Állapot"
 
@@ -353,65 +353,6 @@ msgstr ""
 "ha engedélyezni szeretné $SOURCE_BASE_PATH hogy $ACCESS hozzáférése legyen "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Bemenet:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Adja meg jelszavát"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Jelszó:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux Fix"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Parancs"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Parancs végrehajtása"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Parancs leállítása"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Figyelem: Az Ön felelőssége, hogy a kiadott parancs pontos és helyes legyen"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Még nem futott"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Működésben…"
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Megszakítva, kilépett %d jelzéssel"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Siker"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Hiba, hibakód = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Kész:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/it.po b/framework/po/it.po
index e508952..c5cd919 100644
--- a/framework/po/it.po
+++ b/framework/po/it.po
@@ -18,7 +18,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -28,7 +28,7 @@ msgstr ""
 "it/)\n"
 "Language: it\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -47,9 +47,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "porte %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Sconosciuto"
 
@@ -176,7 +176,7 @@ msgstr "Su questo"
 msgid "Occurred"
 msgstr "Si è verificato"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Stato"
 
@@ -358,66 +358,6 @@ msgstr ""
 "si desidera abilitare $SOURCE_BASE_PATH ad avere accesso $ACCESS al "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Input: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Inserire password"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Password: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Fix SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Comando"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Esegui comando"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Ferma comando"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Attenzione: Si è responsabili della verifica di correttezza di questo "
-"comando"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Non ancora in esecuzione"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Esecuzione in corso..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Interrotto, uscita sul segnale %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Successo"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Fallito, stato di uscita = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Fatto: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/ja.po b/framework/po/ja.po
index 6c8edca..341a07e 100644
--- a/framework/po/ja.po
+++ b/framework/po/ja.po
@@ -17,7 +17,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -27,7 +27,7 @@ msgstr ""
 "ja/)\n"
 "Language: ja\n"
 "Plural-Forms: nplurals=1; plural=0;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -46,9 +46,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "ポート %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "不明"
 
@@ -175,7 +175,7 @@ msgstr "試行の対象"
 msgid "Occurred"
 msgstr "発生回数"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "ステータス"
 
@@ -357,64 +357,6 @@ msgstr ""
 "$TARGET_BASE_PATH $TARGET_CLASS に "
 "$ACCESSアクセスをするために、$SOURCE_BASE_PATHを許可しますか?"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "入力: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "パスワード入力"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "パスワード: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux Fix"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "コマンド"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "コマンドを実行"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "コマンドを停止"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "警告: ユーザーにはこのコマンドが正しいことを確認する責任があります"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "まだ実行しない"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "実行中..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "妨害されました、シグナル %d で終了します"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "成功"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "失敗、終了ステータス = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "完了: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/kn.po b/framework/po/kn.po
index 5be457b..03ff44b 100644
--- a/framework/po/kn.po
+++ b/framework/po/kn.po
@@ -16,7 +16,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -26,7 +26,7 @@ msgstr ""
 "kn/)\n"
 "Language: kn\n"
 "Plural-Forms: nplurals=1; plural=0;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -45,9 +45,9 @@ msgstr "ಪಾಲಿಸಿ;ಸುರಕ್ಷತೆ;selinux;avc;ಅನುಮತ
 msgid "port %s"
 msgstr "ಸಂಪರ್ಕಸ್ಥಾನ %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "ಅಜ್ಞಾತ"
 
@@ -174,7 +174,7 @@ msgstr "ಇಲ್ಲಿ"
 msgid "Occurred"
 msgstr "ಸಂಭವಿಸಿದ್ದು"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "ಸ್ಥಿತಿ"
 
@@ -356,65 +356,6 @@ msgstr ""
 "$TARGET_BASE_PATH $TARGET_CLASS ನಲ್ಲಿ $ACCESS ನಿಲುಕಣೆಯನ್ನು ಹೊಂದುವಂತೆ ನೀವು "
 "$SOURCE_BASE_PATH ಅನ್ನು ಅನುಮತಿಸಬಯಸುವಿರಾ"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ಇನ್‌ಪುಟ್: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "ಗುಪ್ತಪದವನ್ನು ನಮೂದಿಸಿ"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "ಗುಪ್ತಪದ: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux ಪರಿಹಾರ"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "ಆಜ್ಞೆ"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "ಆಜ್ಞೆಯನ್ನು ಚಲಾಯಿಸು"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "ಆಜ್ಞೆಯನ್ನು ನಿಲ್ಲಿಸು"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"ಎಚ್ಚರಿಕೆ: ಈ ಆಜ್ಞೆಯು ಸರಿ ಇದೆಯೆ ಎಂದು ಪರಿಶೀಲಿಸುವ ಜವಾಬ್ದಾರಿಯು ನಿಮ್ಮ ಮೇಲಿದೆ"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "ಇನ್ನೂ ಚಲಾಯಿಸಲ್ಪಟ್ಟಿಲ್ಲ"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "ಚಾಲನೆಯಲ್ಲಿದೆ..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "ತಡೆಯಲಾಗಿದೆ, %d ಸೂಚನೆ ನಂತರ ನಿರ್ಗಮಿಸುತ್ತದೆ"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "ಯಶಸ್ವಿಯಾಗಿದೆ"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "ವಿಫಲಗೊಂಡಿದೆ, ನಿರ್ಗಮನ ಸ್ಥಿತಿ = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "ಆಯಿತು: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/ko.po b/framework/po/ko.po
index 78e541d..8041a69 100644
--- a/framework/po/ko.po
+++ b/framework/po/ko.po
@@ -13,7 +13,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -23,7 +23,7 @@ msgstr ""
 "ko/)\n"
 "Language: ko\n"
 "Plural-Forms: nplurals=1; plural=0;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -42,9 +42,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "포트 %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "알려지지 않음"
 
@@ -171,7 +171,7 @@ msgstr "시도한 곳"
 msgid "Occurred"
 msgstr "발생 횟수"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "상태 "
 
@@ -353,64 +353,6 @@ msgstr ""
 "$ACCESS 접근 권한을 위해 $TARGET_BASE_PATH의 $TARGET_CLASS에 접근하여 $SOURCE_BASE를 허가하고자 "
 "합니다."
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "입력:  "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "암호 입력 "
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "암호:  "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux Fix"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "명령 "
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "명령 실행 "
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "명령 중지 "
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "경고: 이 명령이 올바른지를 확인해야 합니다  "
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "아직 실행하지 않음 "
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "실행 중... "
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "중단되었습니다, %d 신호에서 종료  "
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "성공 "
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "실패, 종료 상태 = %d "
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "완료:  "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/mai.po b/framework/po/mai.po
index f0e3b0d..c2bc30d 100644
--- a/framework/po/mai.po
+++ b/framework/po/mai.po
@@ -9,7 +9,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -19,7 +19,7 @@ msgstr ""
 "mai/)\n"
 "Language: mai\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -38,9 +38,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "अज्ञात"
 
@@ -159,7 +159,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "स्थिति"
 
@@ -337,64 +337,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "इनपुट: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "गुड़किल्ली दाखिल  करू "
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "गुड़किल्ली: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux फिक्स"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "कमांड"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "कमांड चलाउ"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "कमांड रोकू"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "चेतावनी: अहाँ एहि कमांड केँ जाँचबाक लेल उत्तरदायी अछि जे ई सही अछि"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "अखन तकि नहि चललै"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "चलि रहल  अछि ..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "व्यवधान, %d संकेत पर बाहर"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "सफल"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "विफल, स्थिति सँ बाहर निकालू = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "संपन्न: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/ml.po b/framework/po/ml.po
index 1b9dcce..c9a922b 100644
--- a/framework/po/ml.po
+++ b/framework/po/ml.po
@@ -10,7 +10,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -20,7 +20,7 @@ msgstr ""
 "language/ml/)\n"
 "Language: ml\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -39,9 +39,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "പോര്‍ട്ട് %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "അപരിചിതം"
 
@@ -169,7 +169,7 @@ msgstr "ഇതില്‍"
 msgid "Occurred"
 msgstr "സംഭവിച്ചിരിയ്ക്കുന്നു"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "അവസ്ഥ"
 
@@ -351,66 +351,6 @@ msgstr ""
 "$TARGET_BASE_PATH $TARGET_CLASS-ല്‍ $ACCESS പ്രവേശനത്തിനായി നിങ്ങള്‍ "
 "$SOURCE_BASE_PATH അനുവദിയ്ക്കണം"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ഇന്‍പുട്ട്:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "പാസ്‌വേര്‍ഡ് നല്‍കുക"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "പാസ്‌വേര്‍ഡ്:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux ഫിക്സ്"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "കമാന്‍ഡ്"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "കമാന്‍ഡ് പ്രവര്‍ത്തിപ്പിക്കുക"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "കമാന്‍ഡ് നിര്‍ത്തുക"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"മുന്നറിയിപ്പ്: ഈ കമാന്‍ഡ് ശരിയാണോ എന്നുറപ്പാക്കുന്നതിന്റെ ചുമതല "
-"നിങ്ങളുടേതാണ്"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "ഇത് വരെ പ്രവര്‍ത്തിപ്പിച്ചിട്ടില്ല"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "പ്രവര്‍ത്തനത്തിലാണ്..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "തടസ്സപ്പെട്ടു, %d എന്ന സിഗ്നലില്‍ പുറത്ത് കടക്കുക"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "വിജയിച്ചു"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "പരാജയപ്പെട്ടു, പുറത്ത് കടന്ന അവസ്ഥ = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "പൂര്‍ത്തിയായി:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/mr.po b/framework/po/mr.po
index 6fbe30c..7b1de28 100644
--- a/framework/po/mr.po
+++ b/framework/po/mr.po
@@ -12,7 +12,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -22,7 +22,7 @@ msgstr ""
 "mr/)\n"
 "Language: mr\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -41,9 +41,9 @@ msgstr "धोरण;सुरक्षा;selinux;avc;परवानगी;mac
 msgid "port %s"
 msgstr "%s पोर्ट करा"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "अपरिचित"
 
@@ -170,7 +170,7 @@ msgstr "यावर"
 msgid "Occurred"
 msgstr "घडले"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "स्थिती"
 
@@ -352,64 +352,6 @@ msgstr ""
 "$SOURCE_BASE_PATH ला $TARGET_BASE_PATH $TARGET_CLASS करीता $ACCESS प्रवेश "
 "द्याचे आहे"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "इंपुट: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "पासवर्ड प्रविष्ट करा"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "पासवर्ड: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux निर्धारण"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "आदेश"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "आदेश चालवा"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "आदेश थांबवा"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "सावधानी: हा आदेश सदोषीत नाही याच्या तपासणी करीता तुम्ही कारणीभूत आहे"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "अजून कार्यरत नाही"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "कार्यरत आहे..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "अडविले गेले, संकेल %d प्राप्त झाल्यास बाहेर पडा"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "यश"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "अपयशी, बाहेर पडण्याची स्थिती = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "पूर्ण झाले: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/ms.po b/framework/po/ms.po
index 80b6764..04f12c2 100644
--- a/framework/po/ms.po
+++ b/framework/po/ms.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 ")\n"
 "Language: ms\n"
 "Plural-Forms: nplurals=1; plural=0;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Tidak diketahui"
 
@@ -158,7 +158,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr ""
 
@@ -336,64 +336,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr ""
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr ""
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr ""
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr ""
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr ""
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr ""
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr ""
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr ""
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr ""
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr ""
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr ""
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/nb.po b/framework/po/nb.po
index cd29381..f1a4255 100644
--- a/framework/po/nb.po
+++ b/framework/po/nb.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 "language/nb/)\n"
 "Language: nb\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Ukjent"
 
@@ -162,7 +162,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Status"
 
@@ -342,64 +342,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr ""
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr ""
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr ""
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr ""
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr ""
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr ""
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr ""
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr ""
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr ""
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr ""
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr ""
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/nds.po b/framework/po/nds.po
index bd6765a..615f127 100644
--- a/framework/po/nds.po
+++ b/framework/po/nds.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 "language/nds/)\n"
 "Language: nds\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Unbekannt"
 
@@ -158,7 +158,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Tostand"
 
@@ -336,64 +336,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr ""
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Passwoord ingeven:"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Passwoord:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr ""
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr ""
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr ""
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr ""
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr ""
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Lööpt..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Erfolg"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Doon:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/nl.po b/framework/po/nl.po
index de2a0ad..0cd0c4d 100644
--- a/framework/po/nl.po
+++ b/framework/po/nl.po
@@ -11,7 +11,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 ")\n"
 "Language: nl\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "poort %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Onbekend"
 
@@ -169,7 +169,7 @@ msgstr "Op dit"
 msgid "Occurred"
 msgstr "Opgetreden"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Status"
 
@@ -351,66 +351,6 @@ msgstr ""
 "je $SOURCE_BASE_PATH wilt toestaan om $ACCESS toegang te hebben tot de "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Input: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Vul wachtwoord in"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Wachtwoord: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux reparatie"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Commando"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Voer commando uit"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Stop commando"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Waarschuwing: Jij bent verantwoordelijk voor het verifiëren van de "
-"correctheid van dit commando"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Nog niet uitgevoerd"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Uitvoeren..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Onderbroken, exit op signaal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Succes"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Mislukt, exit status = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Klaar: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/or.po b/framework/po/or.po
index 9a80eb6..b85a6bd 100644
--- a/framework/po/or.po
+++ b/framework/po/or.po
@@ -13,7 +13,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -23,7 +23,7 @@ msgstr ""
 ")\n"
 "Language: or\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -42,9 +42,9 @@ msgstr "ନିତୀ;ସୁରକ୍ଷା;selinux;avc;ଅନୁମତି;mac;
 msgid "port %s"
 msgstr "ପୋର୍ଟ %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "ଅଜଣା"
 
@@ -171,7 +171,7 @@ msgstr "ଏହା ଉପରେ"
 msgid "Occurred"
 msgstr "ଘଟିଛି"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "ଅବସ୍ଥିତି"
 
@@ -353,64 +353,6 @@ msgstr ""
 "$TARGET_BASE_PATH $TARGET_CLASS ଉପରେ $ACCESS କୁ ଅଭିଗମ୍ୟତା ଦେବାପାଇଁ ଆପଣ "
 "$SOURCE_BASE_PATH କୁ ଅନୁମତି ଦେବାପାଇଁ ଚାହୁଁଛନ୍ତି"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ନିବେଶ"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "ପ୍ରବେଶ ସଙ୍କେତ ଭରଣକରନ୍ତୁ"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "ପ୍ରବେଶ ସଙ୍କେତ: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux ସ୍ଥିର"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "ନିର୍ଦ୍ଦେଶ"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "ନିର୍ଦ୍ଦେଶ ଚଲାନ୍ତୁ"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "ନିର୍ଦ୍ଦେଶ ଦେବା ବନ୍ଦକରନ୍ତୁ"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "ଚେତାବନୀ: ଏହି ନିର୍ଦ୍ଦେଶଟି ଠିକ ଅଛି ବୋଲି ଯାଞ୍ଚକରିବା ଆପଣଙ୍କ ଦାୟୀତ୍ୱ"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "ଏପର୍ଯ୍ଯନ୍ତ ଚଲାଇନାହିଁ"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "ଚାଲୁଅଛି..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "ବ୍ୟାହତ,ସଙ୍କେତ %d ମିଳିଳାମାତ୍ରେ ପ୍ରସ୍ଥାନକରନ୍ତୁ"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "ସଫଳତା"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "ବିଫଳ, ପ୍ରସ୍ଥାନ ଅବସ୍ଥିତି= %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "କରାଯାଇଛି:  "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/pa.po b/framework/po/pa.po
index f81adbc..ba2e602 100644
--- a/framework/po/pa.po
+++ b/framework/po/pa.po
@@ -11,7 +11,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "language/pa/)\n"
 "Language: pa\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "ਪੋਰਟ %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "ਆਣਜਾਣੀ"
 
@@ -169,7 +169,7 @@ msgstr "ਇਸ ਉੱਪਰ"
 msgid "Occurred"
 msgstr "ਵਾਪਰਿਆ ਹੈ"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "ਸਥਿਤੀ"
 
@@ -351,64 +351,6 @@ msgstr ""
 "ਤੁਸੀਂ $SOURCE_BASE_PATH ਨੂੰ $ACCESS ਪਹੁੰਚ $TARGET_BASE_PATH $TARGET_CLASS "
 "ਉੱਪਰ ਮਨਜੂਰ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ਇੰਪੁੱਟ: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "ਪਾਸਵਰਡ ਦਿਓ"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "ਪਾਸਵਰਡ: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux Fix"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "ਕਮਾਂਡ"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "ਕਮਾਂਡ ਚਲਾਓ"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "ਕਮਾਂਡ ਰੋਕੋ"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "ਚੇਤਾਵਨੀ: ਤੁਸੀਂ ਇਹ ਜਾਂਚ ਕਰਨ ਲਈ ਜੁੰਮੇਵਾਰ ਹੋ ਕਿ ਕਮਾਂਡ ਠੀਕ ਹੈ"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "ਹਾਲੇ ਨਹੀਂ ਚਲਾਈ"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "ਚੱਲ ਰਿਹਾ ਹੈ..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "ਰੋਕਿਆ ਗਿਆ, ਸਿਗਨਲ %d ਤੇ ਬੰਦ ਕਰੋ"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "ਸਫਲਤਾ"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "ਫੇਲ ਹੋਇਆ, exit status = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "ਮੁਕੰਮਲ: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/pl.po b/framework/po/pl.po
index f763780..4da7249 100644
--- a/framework/po/pl.po
+++ b/framework/po/pl.po
@@ -5,23 +5,23 @@
 # Translators:
 # Dimitris Glezos <glezos@transifex.com>, 2011
 # Piotr Drąg <piotrdrag@gmail.com>, 2011-2013
-# Piotr Drąg <piotrdrag@gmail.com>, 2015. #zanata
+# Piotr Drąg <pdrag@aviary.pl>, 2015. #zanata
 msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
 "PO-Revision-Date: 2015-08-28 07:57-0400\n"
-"Last-Translator: Piotr Drąg <piotrdrag@gmail.com>\n"
+"Last-Translator: Piotr Drąg <pdrag@aviary.pl>\n"
 "Language-Team: Polish (http://www.transifex.com/projects/p/fedora/language/"
 "pl/)\n"
 "Language: pl\n"
 "Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 "
 "|| n%100>=20) ? 1 : 2);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -41,9 +41,9 @@ msgstr ""
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Nieznane"
 
@@ -170,7 +170,7 @@ msgstr "W tym"
 msgid "Occurred"
 msgstr "Wystąpiło"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Stan"
 
@@ -352,66 +352,6 @@ msgstr ""
 "należy zezwolić $SOURCE_BASE_PATH na dostęp $ACCESS w $TARGET_BASE_PATH "
 "$TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Wejście: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Proszę podać hasło"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Hasło: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Naprawa SELinuksa"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Polecenie"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Wykonanie polecenia"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Zatrzymanie polecenia"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Ostrzeżenie: użytkownik jest odpowiedzialny za sprawdzenie, czy te polecenie "
-"jest poprawne"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Nie wykonano jeszcze"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Wykonywanie…"
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Przerwano, zakończono po sygnale %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Powodzenie"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Nie powiodło się, stan wyjścia = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Ukończono: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/pt.po b/framework/po/pt.po
index eee433d..6b7218d 100644
--- a/framework/po/pt.po
+++ b/framework/po/pt.po
@@ -13,7 +13,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -23,7 +23,7 @@ msgstr ""
 "language/pt/)\n"
 "Language: pt\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -42,9 +42,9 @@ msgstr ""
 msgid "port %s"
 msgstr "porto %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Desconhecido"
 
@@ -171,7 +171,7 @@ msgstr "Nesta"
 msgid "Occurred"
 msgstr "Ocorreu"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Estado"
 
@@ -353,65 +353,6 @@ msgstr ""
 "quer permitir $SOURCE_BASE_PATH para ter acesso $ACCESS sobre o "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Entrada: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Digite a Senha"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Senha: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Corrigir SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Commando"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Executar Comando"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Parar Comando"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Atenção: Você é responsável por verificar que este comando está correcto"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Ainda Não Executou"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Em execução..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Interrompido, sair com o sinal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Sucesso"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Falhou, estado de saída = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Concluído: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/pt_BR.po b/framework/po/pt_BR.po
index f6b2555..9b3a06e 100644
--- a/framework/po/pt_BR.po
+++ b/framework/po/pt_BR.po
@@ -21,7 +21,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -31,7 +31,7 @@ msgstr ""
 "fedora/language/pt_BR/)\n"
 "Language: pt-BR\n"
 "Plural-Forms: nplurals=2; plural=(n > 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -50,9 +50,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "porta %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Desconhecido"
 
@@ -179,7 +179,7 @@ msgstr "Nesta"
 msgid "Occurred"
 msgstr "Ocorreu"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Status"
 
@@ -361,64 +361,6 @@ msgstr ""
 "Você quer permitir que $SOURCE_BASE_PATH tenha acesso $ACCESS no "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Entrada: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Digite a senha"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Senha: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Correção do SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Comando"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Executar comando"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Parar comando"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Aviso: você é responsável por verificar se este comando está correto"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Não está executando ainda"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Executando..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Interrompido, com saída pelo sinal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Sucesso"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Falhou, status de saída = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Concluído: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/ru.po b/framework/po/ru.po
index 3da39a9..277605f 100644
--- a/framework/po/ru.po
+++ b/framework/po/ru.po
@@ -21,7 +21,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -32,7 +32,7 @@ msgstr ""
 "Language: ru\n"
 "Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
 "n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -51,9 +51,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "порт %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Неизвестно"
 
@@ -180,7 +180,7 @@ msgstr "На этом"
 msgid "Occurred"
 msgstr "Повтор"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Статус"
 
@@ -362,64 +362,6 @@ msgstr ""
 "вы хотите предоставить $SOURCE_BASE_PATH доступ $ACCESS к $TARGET_BASE_PATH "
 "$TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Ввод:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Введите пароль"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Пароль:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Исправление SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Команда"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Выполнить команду"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Остановить команду"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Внимание: Дважды проверьте правильность вводимой команды"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Еще не выполнена"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Выполняется..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Прервано, выход по сигналу %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Успешно"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Ошибка. Статус выхода: %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Готово:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/sk.po b/framework/po/sk.po
index 6038d8d..1ba62fb 100644
--- a/framework/po/sk.po
+++ b/framework/po/sk.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 "sk/)\n"
 "Language: sk\n"
 "Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Neznáme"
 
@@ -163,7 +163,7 @@ msgstr "Na tomto"
 msgid "Occurred"
 msgstr "Vyskytnuté"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Stav"
 
@@ -343,64 +343,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Vstup: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Zadajte heslo"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Heslo: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux oprava"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Príkaz"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Spustiť príkaz"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Zastaviť príkaz"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Upozornenie: Ste zodpovedný za to, aby bol tento príkaz správny"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Zatiaľ nespustené"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Spúšťa sa..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr ""
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Úspešné"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr ""
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Hotovo: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/sr.po b/framework/po/sr.po
index 491f0fe..6cdc0d2 100644
--- a/framework/po/sr.po
+++ b/framework/po/sr.po
@@ -10,7 +10,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "Language: sr\n"
 "Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
 "n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Непознато"
 
@@ -161,7 +161,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Стање"
 
@@ -339,64 +339,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Унос: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Унесите лозинку"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Лозинка: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux поправка"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Наредба"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Покрени наредбу"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Заустави наредбу"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Упозорење: одговорни сте за проверу исправности ове наредбе"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Није покренуто"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Покренуто..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Прекинуто, изашао на знак %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Успешно"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Неуспешно, излазно стање = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Готово: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/sr@latin.po b/framework/po/sr@latin.po
index 6295c00..a7915f2 100644
--- a/framework/po/sr@latin.po
+++ b/framework/po/sr@latin.po
@@ -10,7 +10,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "Language: sr@latin\n"
 "Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
 "n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Nepoznato"
 
@@ -161,7 +161,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Stanje"
 
@@ -339,64 +339,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Unos: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Unesite lozinku"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Lozinka: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux popravka"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Naredba"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Pokreni naredbu"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Zaustavi naredbu"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Upozorenje: odgovorni ste za proveru ispravnosti ove naredbe"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Nije pokrenuto"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Pokrenuto..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Prekinuto, izašao na znak %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Uspešno"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Neuspešno, izlazno stanje = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Gotovo: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/sv.po b/framework/po/sv.po
index 52e892f..00b228e 100644
--- a/framework/po/sv.po
+++ b/framework/po/sv.po
@@ -10,7 +10,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -20,7 +20,7 @@ msgstr ""
 "sv/)\n"
 "Language: sv\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -39,9 +39,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Okänd"
 
@@ -168,7 +168,7 @@ msgstr "På denna"
 msgid "Occurred"
 msgstr "Inträffade"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Status"
 
@@ -350,65 +350,6 @@ msgstr ""
 "du vill tillåta $SOURCE_BASE_PATH att ha $ACCESS till $TARGET_CLASS "
 "$TARGET_BASE_PATH"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Indata: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Ange lösenord"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Lösenord: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinuxlagning"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Kommando"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Kör kommando"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Stoppa kommando"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr ""
-"Varning: Du är ansvarig för att verifiera att detta kommando är riktigt"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Inte kört ännu"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Kör..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Avbrutet, avslutade med signal %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Klar"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Misslyckades, slutstatus = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Klart: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/ta.po b/framework/po/ta.po
index e9e29f2..1f1abe3 100644
--- a/framework/po/ta.po
+++ b/framework/po/ta.po
@@ -15,7 +15,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -25,7 +25,7 @@ msgstr ""
 ")\n"
 "Language: ta\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -44,9 +44,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "துறை %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "தெரியாதது"
 
@@ -173,7 +173,7 @@ msgstr "இதில்"
 msgid "Occurred"
 msgstr "ஏற்பட்டது"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "நிலை"
 
@@ -355,64 +355,6 @@ msgstr ""
 "$SOURCE_BASE_PATH ஐ $ACCESS அணுகலை $TARGET_BASE_PATH $TARGET_CLASS இல் "
 "அனுமதிக்க விருப்பவும்"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "உள்ளீடு:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "கடவுச்சொல் உள்ளிடவும்"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "கடவுச்சொல்:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux திருத்தம்"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "கட்டளை"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "கட்டளையை இயக்குதல்"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "கட்டளையை நிறுத்துதல்"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "எச்சரிக்கை: இந்த கட்டளை சரியானதா என சோதிப்பது உங்கள் பொறுப்பு"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "இன்னும் இயங்கவில்லை"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "இயங்குகிறது..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "இடைஞ்சல், சிக்னல் %d வெளியேறுகிறது"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "வெற்றி"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "செயலிழக்கப்பட்டது, வெளியேற்ற நிலை = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "முடிந்தது:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/te.po b/framework/po/te.po
index 7db80bb..775c85e 100644
--- a/framework/po/te.po
+++ b/framework/po/te.po
@@ -11,7 +11,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "te/)\n"
 "Language: te\n"
 "Plural-Forms: nplurals=2; plural=(n != 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -40,9 +40,9 @@ msgstr "విధానం;రక్షణ;selinux;avc;అనుమతి;mac;
 msgid "port %s"
 msgstr "పోర్ట్ %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "తెలియని"
 
@@ -169,7 +169,7 @@ msgstr "దీనిపై"
 msgid "Occurred"
 msgstr "ఎదురైంది"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "స్థితి"
 
@@ -351,64 +351,6 @@ msgstr ""
 "$TARGET_BASE_PATH $TARGET_CLASS పై $ACCESS యాక్సెస్ కలిగివుండుటకు మీరు "
 "$SOURCE_BASE_PATH ను అనుమతించుదామని అనుకొనుచున్నారా"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "ఇన్‌పుట్: "
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "సంకేతపదాన్ని ప్రవేశపెట్టుము"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "సంకేతపదము: "
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux ఫిక్స్‍"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "ఆదేశము"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "ఆదేశాన్ని నడుపుము"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "ఆదేశాన్ని ఆపుము"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "హెచ్చరిక: ఈ ఆదేశం ఖచ్చితమైంది అనుటకు మీరే మొత్తముకు భాద్యులు"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "ఇంతవరకు నడువలేదు"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "నడుస్తోంది..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "అవరోధించబడింది, సంజ్ఞ %d పైన బయటకువచ్చింది"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "సఫలం"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "విఫలమైంది, నిష్క్రమణ స్థితి = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "అయినది: "
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/th.po b/framework/po/th.po
index a2b0072..74eca21 100644
--- a/framework/po/th.po
+++ b/framework/po/th.po
@@ -8,7 +8,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -18,7 +18,7 @@ msgstr ""
 ")\n"
 "Language: th\n"
 "Plural-Forms: nplurals=1; plural=0;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -37,9 +37,9 @@ msgstr ""
 msgid "port %s"
 msgstr ""
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "ไม่ทราบ"
 
@@ -158,7 +158,7 @@ msgstr ""
 msgid "Occurred"
 msgstr ""
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "สถานะ"
 
@@ -336,64 +336,6 @@ msgid ""
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "นำเข้า:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "ใส่รหัสผ่าน"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "รหัสผ่าน:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "ซ่อมแซม SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "คำสั่ง"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "เรียกใช้คำสั่ง"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "หยุดคำสั่ง"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "คำเตือน: คุณต้องตรวจสอบว่าคำสั่งนี้ถูกต้องด้วยตัวเอง"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "ยังไม่ได้เรียกใช้"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "กำลังเรียกใช้..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "ถูกขัดจังหวะและได้ออกตามสัญญาณ %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "สำเร็จ"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "ล้มเหลว สถานะการออก = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "เสร็จแล้ว:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/tr.po b/framework/po/tr.po
index 1173e7c..a70f179 100644
--- a/framework/po/tr.po
+++ b/framework/po/tr.po
@@ -9,7 +9,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -19,7 +19,7 @@ msgstr ""
 "tr/)\n"
 "Language: tr\n"
 "Plural-Forms: nplurals=2; plural=(n > 1);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -38,9 +38,9 @@ msgstr ""
 msgid "port %s"
 msgstr "port %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Bilinmeyen"
 
@@ -163,7 +163,7 @@ msgstr ""
 msgid "Occurred"
 msgstr "Meydana geldi"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Durum"
 
@@ -345,64 +345,6 @@ msgstr ""
 "$TARGET_BASE_PATH $TARGET_CLASS üzerinde $ACCESS  erişim hakkına sahip olmak "
 "için $SOURCE_BASE_PATH e izin vermelisiniz"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Girdi:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Şifre gir"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Şifre:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux Düzeltildi"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Komut"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Komutu Çalıştır"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Komutu Durdur"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Uyarı: Bu komutun doğru olduğundan siz sorumlusunuz."
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Henüz çalışmadı"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Çalışıyor..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Kesildi, %d sinyaliyle çıkış"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Başarılı"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Başarısız, %d durumuyla çıkış"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Bitti:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/uk.po b/framework/po/uk.po
index 54416d9..3c51a36 100644
--- a/framework/po/uk.po
+++ b/framework/po/uk.po
@@ -10,7 +10,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -21,7 +21,7 @@ msgstr ""
 "Language: uk\n"
 "Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && "
 "n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -41,9 +41,9 @@ msgstr ""
 msgid "port %s"
 msgstr "порт %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "Невідомо"
 
@@ -170,7 +170,7 @@ msgstr "У цей"
 msgid "Occurred"
 msgstr "Сталося"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "Статус"
 
@@ -352,64 +352,6 @@ msgstr ""
 "якщо ви бажаєте дозволити $SOURCE_BASE_PATH мати доступ $ACCESS до "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "Ввід:"
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "Введіть пароль"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "Пароль:"
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "Виправлення SELinux"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "Команда"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "Запустити команду"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "Зупинити команду"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "Попередження: Двічі перевірте правильність вводу команди"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "Ще не виконана"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "Виконується..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "Перервано, вихід за сигналом %d"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "Успішно"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "Помилка. Статус завершення: %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "Завершено:"
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
diff --git a/framework/po/zh_CN.po b/framework/po/zh_CN.po
index 5cc4149..454955e 100644
--- a/framework/po/zh_CN.po
+++ b/framework/po/zh_CN.po
@@ -11,22 +11,22 @@
 # Wei Liu <LLIU@REDHAT.COM>, 2012-2013
 # Xi Huang <xhuang@redhat.com>, 2006
 # yusuf <yusufma77@yahoo.com>, 2011
-# Leah Liu <lliu@redhat.com>, 2016. #zanata
+# Tian Shixiong <tiansworld@gmail.com>, 2016. #zanata
 msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
-"PO-Revision-Date: 2016-03-03 12:17-0500\n"
-"Last-Translator: Leah Liu <lliu@redhat.com>\n"
+"PO-Revision-Date: 2016-05-28 06:05-0400\n"
+"Last-Translator: Tian Shixiong <tiansworld@gmail.com>\n"
 "Language-Team: Chinese (China) (http://www.transifex.com/projects/p/fedora/"
 "language/zh_CN/)\n"
 "Language: zh-CN\n"
 "Plural-Forms: nplurals=1; plural=0;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -45,9 +45,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "端口 %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "未知"
 
@@ -171,9 +171,9 @@ msgstr "对这个"
 
 #: ../src/setroubleshoot/browser.py:270
 msgid "Occurred"
-msgstr "发生"
+msgstr "已发生的"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "状态"
 
@@ -201,7 +201,7 @@ msgstr "<b>如果您本来想要...</b>"
 
 #: ../src/setroubleshoot/browser.py:394
 msgid "<b>Then this is the solution.</b>"
-msgstr "<b>那么这些是解决方案。</b>"
+msgstr "<b>那么这是解决方案。</b>"
 
 #: ../src/setroubleshoot/browser.py:413 ../src/setroubleshoot/browser.py:549
 msgid "If "
@@ -222,7 +222,7 @@ msgstr "报告\n"
 #: ../src/setroubleshoot/browser.py:544
 #, python-format
 msgid "Plugin: %s "
-msgstr "插件： %s "
+msgstr "插件：%s "
 
 #: ../src/setroubleshoot/browser.py:611
 msgid "Unable to grant access."
@@ -231,12 +231,12 @@ msgstr "未能准予访问"
 #: ../src/setroubleshoot/browser.py:642 ../src/setroubleshoot/browser.py:784
 #, python-format
 msgid "Alert %d of %d"
-msgstr "警报 %d of %d"
+msgstr "警报 %d，共 %d 个"
 
 #: ../src/setroubleshoot/browser.py:767
 #, python-format
 msgid "On this %s:"
-msgstr "对这个 %s："
+msgstr "关于此 %s："
 
 #: ../src/setroubleshoot/browser.py:815 ../src/setroubleshoot/browser.py:821
 #: ../src/setroubleshoot/signature.py:391
@@ -352,65 +352,7 @@ msgid ""
 "you want to allow $SOURCE_BASE_PATH to have $ACCESS access on the "
 "$TARGET_BASE_PATH $TARGET_CLASS"
 msgstr ""
-"您想要允许 $SOURCE_BASE_PATH 以 $ACCESS 方式访问 $TARGET_BASE_PATH $TARGET_CLASS"
-
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "输入："
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "输入密码"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "密码："
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux 修正"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "命令"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "运行命令"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "终止命令"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "警告：您需要自己确认该命令是正确的"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "还没有运行"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "运行中......"
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "中断，在信号 %d 后退出"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "成功"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "失败，退出状态 = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "完成："
+"您想要允许 $SOURCE_BASE_PATH 在 $TARGET_BASE_PATH $TARGET_CLASS 上拥有 $ACCESS 访问权限"
 
 #: ../src/setroubleshoot/server.py:191
 #, python-format
@@ -420,7 +362,7 @@ msgstr "如需要完整的 SELinux 信息，请运行 sealert -l %s"
 #: ../src/setroubleshoot/server.py:377
 #, python-format
 msgid "The user (%s) cannot modify data for (%s)"
-msgstr "用户（%s）无法为（%s）修改数据"
+msgstr "用户 (%s) 无法为 (%s) 修改数据"
 
 #: ../src/setroubleshoot/server.py:440 ../src/sealert:291
 msgid "Started"
@@ -436,7 +378,7 @@ msgstr "核查侦听程序"
 
 #: ../src/setroubleshoot/signature.py:74
 msgid "Never Ignore"
-msgstr "永不忽略"
+msgstr "从不忽略"
 
 #: ../src/setroubleshoot/signature.py:75
 msgid "Ignore Always"
@@ -452,11 +394,11 @@ msgstr "目录"
 
 #: ../src/setroubleshoot/signature.py:194
 msgid "semaphore"
-msgstr "信号量"
+msgstr "semaphore"
 
 #: ../src/setroubleshoot/signature.py:195
 msgid "shared memory"
-msgstr "共享存储器"
+msgstr "共享的内存"
 
 #: ../src/setroubleshoot/signature.py:196
 msgid "message queue"
@@ -493,21 +435,21 @@ msgstr "权能"
 #: ../src/setroubleshoot/signature.py:376
 #, python-format
 msgid "%s has a permissive type (%s). This access was not denied."
-msgstr "%s 有一个容许类型 (%s)。此访问未受拒绝。"
+msgstr "%s 有一个容许类型 (%s)。此访问未被拒绝。"
 
 #: ../src/setroubleshoot/signature.py:379
 msgid "SELinux is in permissive mode. This access was not denied."
-msgstr "SELinux 在 permissive 模式。这次访问没有被拒绝。"
+msgstr "SELinux 在 permissive 模式。此访问未被拒绝。"
 
 #: ../src/setroubleshoot/signature.py:432
 #, python-format
 msgid "SELinux is preventing %s from using the %s access on a process."
-msgstr "SELinux 正在阻止 %s 使用对进程 %s 的访问。"
+msgstr "SELinux 正在阻止 %s 在进程中使用 %s 访问。"
 
 #: ../src/setroubleshoot/signature.py:432
 #, python-format
 msgid "SELinux is preventing %s from using the '%s' accesses on a process."
-msgstr "SELinux 正在阻止 %s 对某个进程使用 '%s' 访问。"
+msgstr "SELinux 正在阻止 %s 在进程中使用 %s 访问。"
 
 #: ../src/setroubleshoot/signature.py:435
 #, python-format
@@ -522,22 +464,22 @@ msgstr "SELinux 正在阻止 %s 使用 '%s' 功能。"
 #: ../src/setroubleshoot/signature.py:437
 #, python-format
 msgid "SELinux is preventing %s from %s access on the %s labeled %s."
-msgstr "SELinux 正在阻止 %s 在标记为 %s 的 %s 访问 %s。"
+msgstr "SELinux is preventing %s from %s access on the %s labeled %s."
 
 #: ../src/setroubleshoot/signature.py:437
 #, python-format
 msgid "SELinux is preventing %s from '%s' accesses on the %s labeled %s."
-msgstr "SELinux 正在阻止 %s 在标记为 %s 的 %s 访问 '%s'。"
+msgstr "SELinux is preventing %s from '%s' accesses on the %s labeled %s."
 
 #: ../src/setroubleshoot/signature.py:438
 #, python-format
 msgid "SELinux is preventing %s from %s access on the %s %s."
-msgstr "SELinux 正在阻止 %s 在 %s %s 访问 %s。"
+msgstr "SELinux is preventing %s from %s access on the %s %s."
 
 #: ../src/setroubleshoot/signature.py:438
 #, python-format
 msgid "SELinux is preventing %s from '%s' accesses on the %s %s."
-msgstr "SELinux 正在阻止 %s 在 %s %s 访问 '%s'。"
+msgstr "SELinux is preventing %s from '%s' accesses on the %s %s."
 
 #: ../src/setroubleshoot/signature.py:469
 msgid "Additional Information:\n"
@@ -545,11 +487,11 @@ msgstr "更多信息:\n"
 
 #: ../src/setroubleshoot/signature.py:470
 msgid "Source Context"
-msgstr "源上下文"
+msgstr "源环境 (Context)"
 
 #: ../src/setroubleshoot/signature.py:471
 msgid "Target Context"
-msgstr "目标上下文"
+msgstr "目标环境"
 
 #: ../src/setroubleshoot/signature.py:472
 msgid "Target Objects"
@@ -586,7 +528,7 @@ msgstr "策略 RPM"
 
 #: ../src/setroubleshoot/signature.py:483
 msgid "Selinux Enabled"
-msgstr "Selinux 已经激活"
+msgstr "Selinux 已启用"
 
 #: ../src/setroubleshoot/signature.py:484
 msgid "Policy Type"
@@ -675,7 +617,7 @@ msgstr "当前的： %s "
 #: ../src/updater.py:27
 #, python-format
 msgid "newer: %s "
-msgstr "更新的： %s "
+msgstr "新的： %s "
 
 #: ../src/seapplet.c:189
 msgid "New SELinux security alert"
@@ -683,7 +625,7 @@ msgstr "新 SELinux 安全性警报"
 
 #: ../src/seapplet.c:189
 msgid "AVC denial, click icon to view"
-msgstr "AVC 拒绝，点击图标查看"
+msgstr "AVC 拒绝信息，点击图标查看"
 
 #: ../src/seapplet.c:195 ../src/seapplet.c:246
 msgid "Dismiss"
@@ -696,11 +638,11 @@ msgstr "显示"
 #. set tooltip
 #: ../src/seapplet.c:440 ../src/sealert:64
 msgid "SELinux AVC denial, click to view"
-msgstr "SELinux AVC 拒绝，点击查看"
+msgstr "SELinux AVC 拒绝信息，点击查看"
 
 #: ../src/sealert:103
 msgid "SELinux not enabled, sealert will not run on non SELinux systems"
-msgstr "SELinux 没有激活，sealert 无法在非 SELinux 系统上运行"
+msgstr "SELinux 没有启用，sealert 无法在非 SELinux 系统上运行"
 
 #: ../src/sealert:150
 msgid "Not fixable."
@@ -718,7 +660,7 @@ msgstr "插件 %s 对 %s id 无效"
 
 #: ../src/setroubleshootd:73
 msgid "SELinux not enabled, setroubleshootd exiting..."
-msgstr "SELinux 没有激活，setroubleshootd 正在退出..."
+msgstr "SELinux 没有启用，setroubleshootd 正在退出..."
 
 #: ../src/setroubleshootd:105
 #, c-format
@@ -761,17 +703,17 @@ msgstr "关闭警报弹出窗口。"
 
 #: ../gui/browser.glade.h:21
 msgid "On this file:"
-msgstr "对这个文件："
+msgstr "关于此文件："
 
 #: ../gui/browser.glade.h:22
 msgid "label"
-msgstr "标签"
+msgstr "标记"
 
 #: ../gui/browser.glade.h:23
 msgid ""
 "Read alert troubleshoot information.  May require administrative privileges "
 "to remedy."
-msgstr "阅读警报故障排除信息。可能需要管理员权限才能纠正。"
+msgstr "阅读警报故障排除信息。可能需要管理员权限才能修复。"
 
 #: ../gui/browser.glade.h:25
 msgid "Email alert to system administrator."
@@ -795,11 +737,11 @@ msgstr "列出数据库中所有警报。"
 
 #: ../gui/bug_report.glade.h:1
 msgid "Review and Submit Bug Report"
-msgstr "预览并提交 Bug 报告"
+msgstr "检查并提交 Bug 报告"
 
 #: ../gui/bug_report.glade.h:2
 msgid "<span size='large' weight='bold'>Review and Submit Bug Report</span>"
-msgstr "<span size='large' weight='bold'>预览并提交 Bug 报告</span>"
+msgstr "<span size='large' weight='bold'>检查并提交 Bug 报告</span>"
 
 #: ../gui/bug_report.glade.h:3
 msgid ""
diff --git a/framework/po/zh_TW.po b/framework/po/zh_TW.po
index a823b57..862cfd9 100644
--- a/framework/po/zh_TW.po
+++ b/framework/po/zh_TW.po
@@ -12,7 +12,7 @@ msgid ""
 msgstr ""
 "Project-Id-Version: PACKAGE VERSION\n"
 "Report-Msgid-Bugs-To: \n"
-"POT-Creation-Date: 2016-01-15 16:27+0100\n"
+"POT-Creation-Date: 2016-04-15 20:42+0200\n"
 "MIME-Version: 1.0\n"
 "Content-Type: text/plain; charset=UTF-8\n"
 "Content-Transfer-Encoding: 8bit\n"
@@ -22,7 +22,7 @@ msgstr ""
 "language/zh_TW/)\n"
 "Language: zh-TW\n"
 "Plural-Forms: nplurals=1; plural=0;\n"
-"X-Generator: Zanata 3.8.3\n"
+"X-Generator: Zanata 3.8.4\n"
 
 #: ../setroubleshoot.desktop.in.h:1
 msgid "SELinux Troubleshooter"
@@ -41,9 +41,9 @@ msgstr "policy;security;selinux;avc;permission;mac;alert;sealert;"
 msgid "port %s"
 msgstr "連接埠 %s"
 
-#: ../src/setroubleshoot/audit_data.py:905
-#: ../src/setroubleshoot/browser.py:747 ../src/setroubleshoot/browser.py:822
-#: ../src/setroubleshoot/rpc.py:528 ../src/setroubleshoot/util.py:229
+#: ../src/setroubleshoot/audit_data.py:905 ../src/setroubleshoot/browser.py:747
+#: ../src/setroubleshoot/browser.py:822 ../src/setroubleshoot/rpc.py:528
+#: ../src/setroubleshoot/util.py:229
 msgid "Unknown"
 msgstr "未知"
 
@@ -169,7 +169,7 @@ msgstr "它"
 msgid "Occurred"
 msgstr "發生"
 
-#: ../src/setroubleshoot/browser.py:270 ../src/run_cmd.py:406
+#: ../src/setroubleshoot/browser.py:270
 msgid "Status"
 msgstr "狀態"
 
@@ -350,64 +350,6 @@ msgid ""
 msgstr ""
 "您想要允許 $SOURCE_BASE_PATH 對 $TARGET_BASE_PATH $TARGET_CLASS 有 $ACCESS 存取權"
 
-#: ../src/run_cmd.py:172
-msgid "Input: "
-msgstr "輸入："
-
-#: ../src/run_cmd.py:255
-msgid "Enter Password"
-msgstr "輸入密碼"
-
-#: ../src/run_cmd.py:268
-msgid "Password: "
-msgstr "密碼："
-
-#: ../src/run_cmd.py:367
-msgid "SELinux Fix"
-msgstr "SELinux 修正"
-
-#: ../src/run_cmd.py:378
-msgid "Command"
-msgstr "指令"
-
-#: ../src/run_cmd.py:388
-msgid "Run Command"
-msgstr "執行指令"
-
-#: ../src/run_cmd.py:391
-msgid "Stop Command"
-msgstr "停止指令"
-
-#: ../src/run_cmd.py:413
-msgid "Warning: You are responsible for verifying this command is correct"
-msgstr "警告：您必須負責驗證這項指令是否正確"
-
-#: ../src/run_cmd.py:455
-msgid "Not Run Yet"
-msgstr "還未執行"
-
-#: ../src/run_cmd.py:466
-msgid "Running..."
-msgstr "執行中..."
-
-#: ../src/run_cmd.py:481
-#, python-format
-msgid "Interrupted, exit on signal %d"
-msgstr "已被干擾，於信號 %d 退出"
-
-#: ../src/run_cmd.py:483
-msgid "Success"
-msgstr "成功"
-
-#: ../src/run_cmd.py:485
-#, python-format
-msgid "Failed, exit status = %d"
-msgstr "失敗，退出狀態 = %d"
-
-#: ../src/run_cmd.py:487
-msgid "Done: "
-msgstr "完成："
-
 #: ../src/setroubleshoot/server.py:191
 #, python-format
 msgid " For complete SELinux messages. run sealert -l %s"
-- 
2.7.4

